### ISSUE TITLE
Cache database meta-data

### ISSUE THREAD

**Issue by macbre** [macbre/index-digest#57]
- [x] cache the list of tables
- [x] cache the list of columns
- [x] cache the list of indices
- [x] cache `EXPLAIN` queries
- [x] cache MySQL server version

Use [`memoize` decorator](https://wiki.python.org/moin/PythonDecoratorLibrary#Memoize) / https://medium.com/@nkhaja/memoization-and-decorators-with-python-32f607439f84

Queries performed when running `make demo`

* before the fix: **101**
* after the fix: **67**

### Repeated queries

```sql
EXPLAIN select count(*) from 0002_not_used_indices where foo = 'foo'
EXPLAIN select * from 0002_not_used_indices where bar = 'foo'
EXPLAIN select * from 0002_not_used_indices order by id
EXPLAIN select * from 0002_not_used_indices where foo = 'foo' and id = 2
```
